/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;
import potionprodigy.Player;
import potionprodigy.ItemStack;
import potionprodigy.Inventory;
import gui.components.ItemCard;
import gui.components.Theme;
import java.util.Stack;

/**
 * Displays the player's ingredient quantities and usable and unusable
 * cauldron counts.
 */
public class InventoryPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private Controller controller;
    
    /**
     * Creates an inventory panel connected to the application.
     *
     * @param mainFrame application window used for navigation
     * @param controller controller providing the current player
     */
    public InventoryPanel(MainFrame mainFrame, Controller controller) {
        initComponents();
        inventoryItemsPanel.setLayout(new java.awt.GridLayout(0, 4, 12, 12));
        inventoryItemsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        inventoryScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        
        this.mainFrame = mainFrame;
        this.controller = controller;
    }
    /**
     * Rebuilds the inventory card list using the current player's latest data.
     */
    public void refreshDisplay() {
        inventoryItemsPanel.removeAll();
        Stack<ItemStack> bases = new Stack<>();

        Player player = controller.getCurrentPlayer();

        if (player != null) {
            for (ItemStack stack : player.getInventory().getIngredientStacks()) {
                if (stack.getQuantity() > 0 && stack.getIngredient().getName().contains("BASE")) {
                    bases.push(stack);
                } else if (stack.getQuantity() > 0 && !stack.getIngredient().getName().contains("BASE")) {
                    ItemCard card = new ItemCard(stack);
                    Theme.apply(card);
                    inventoryItemsPanel.add(card);
                }
            }
            
            for (ItemStack stack : bases) {
                ItemCard card = new ItemCard(stack);
                Theme.apply(card);
                inventoryItemsPanel.add(card);
            }
        }

        Inventory inventory = player.getInventory();

        lblCauldrons.setText("Cauldrons: " + inventory.countUsableCauldrons()
                + " usable / " + inventory.countUnusableCauldrons() + " unusable");

        inventoryItemsPanel.revalidate();
        inventoryItemsPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        inventoryScrollPane = new javax.swing.JScrollPane();
        inventoryItemsPanel = new javax.swing.JPanel();
        lblCauldrons = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        lblTitle.setText("Inventory:");

        inventoryScrollPane.setBorder(null);

        inventoryItemsPanel.setLayout(new java.awt.GridLayout(10, 0, 4, 10));
        inventoryScrollPane.setViewportView(inventoryItemsPanel);

        lblCauldrons.setText("jLabel1");

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inventoryScrollPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lblCauldrons))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle)))
                        .addGap(0, 411, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCauldrons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Returns to the main menu.
     *
     * @param evt generated button action event
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.showMainMenu();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel inventoryItemsPanel;
    private javax.swing.JScrollPane inventoryScrollPane;
    private javax.swing.JLabel lblCauldrons;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
