/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;
import potionprodigy.Player;
import potionprodigy.ItemStack;
import potionprodigy.Inventory;
import gui.components.ItemCard;
import java.util.Stack;

/**
 *
 * @author YJ
 */
public class InventoryPanel extends javax.swing.JPanel {
    MainFrame mainFrame;
    Controller controller;
    
    /**
     * Creates new form InventoryPanel
     */
    public InventoryPanel() {
        initComponents();
    }
    
    public InventoryPanel(MainFrame mainFrame, Controller controller) {
        initComponents();
        
        inventoryItemsPanel.setLayout(new java.awt.GridLayout(0, 4, 10, 10));

        inventoryScrollPane.getVerticalScrollBar().setUnitIncrement(15);

        this.mainFrame = mainFrame;
        this.controller = controller;

        // num of row, cols; px gap h, v
        inventoryItemsPanel.setLayout(new java.awt.GridLayout(0, 4, 12, 12));

        inventoryItemsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
    }
    
    public void refreshDisplay() {
        inventoryItemsPanel.removeAll();
        Stack<ItemStack> bases = new Stack<>();

        Player player = controller.getCurrentPlayer();

        if (player != null) {
            for (ItemStack stack : player.getInventory().getIngredientStacks()) {
                if (stack.getQuantity() > 0 && stack.getIngredient().getName().contains("BASE")) {
                    bases.push(stack);
                } else if (stack.getQuantity() > 0 && !stack.getIngredient().getName().contains("BASE")) {
                    ItemCard card = new ItemCard(stack);
                    inventoryItemsPanel.add(card);
                }
            }
            
            for (ItemStack stack : bases) {
                ItemCard card = new ItemCard(stack);
                inventoryItemsPanel.add(card);
            }
        }

        Inventory inventory = player.getInventory();

        lblCauldrons.setText("Cauldrons: " + inventory.countUsableCauldrons()
                + " usable / " + inventory.countUnusableCauldrons() + " unusable");

        inventoryItemsPanel.revalidate();
        inventoryItemsPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        inventoryScrollPane = new javax.swing.JScrollPane();
        inventoryItemsPanel = new javax.swing.JPanel();
        lblCauldrons = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        lblTitle.setText("Inventory:");

        inventoryItemsPanel.setLayout(new java.awt.GridLayout(10, 0, 4, 10));
        inventoryScrollPane.setViewportView(inventoryItemsPanel);

        lblCauldrons.setText("jLabel1");

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inventoryScrollPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lblCauldrons))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle)))
                        .addGap(0, 395, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCauldrons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.showMainMenu();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel inventoryItemsPanel;
    private javax.swing.JScrollPane inventoryScrollPane;
    private javax.swing.JLabel lblCauldrons;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
