/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author YJ
 */
public class MainMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblCrystals = new javax.swing.JLabel();
        btnBrew = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnSpellbook = new javax.swing.JButton();
        btnMarket = new javax.swing.JButton();
        btnBlessCauldron = new javax.swing.JButton();
        btnLoginBonus = new javax.swing.JButton();
        btnSaveAndExit = new javax.swing.JButton();

        lblWelcome.setText("Welcome");

        lblCrystals.setText("Crystals");

        btnBrew.setText("Brew A Potion");

        btnInventory.setText("Open Inventory");

        btnSpellbook.setText("Open Spellbook");

        btnMarket.setText("Visit Market");

        btnBlessCauldron.setText("Bless Cauldron");

        btnLoginBonus.setText("Login Bonus");

        btnSaveAndExit.setText("Save & Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveAndExit)
                    .addComponent(btnLoginBonus)
                    .addComponent(btnBlessCauldron)
                    .addComponent(btnMarket)
                    .addComponent(btnSpellbook)
                    .addComponent(btnInventory)
                    .addComponent(btnBrew)
                    .addComponent(lblCrystals)
                    .addComponent(lblWelcome))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCrystals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBrew)
                .addGap(18, 18, 18)
                .addComponent(btnInventory)
                .addGap(18, 18, 18)
                .addComponent(btnSpellbook)
                .addGap(18, 18, 18)
                .addComponent(btnMarket)
                .addGap(18, 18, 18)
                .addComponent(btnBlessCauldron)
                .addGap(18, 18, 18)
                .addComponent(btnLoginBonus)
                .addGap(18, 18, 18)
                .addComponent(btnSaveAndExit)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlessCauldron;
    private javax.swing.JButton btnBrew;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLoginBonus;
    private javax.swing.JButton btnMarket;
    private javax.swing.JButton btnSaveAndExit;
    private javax.swing.JButton btnSpellbook;
    private javax.swing.JLabel lblCrystals;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
