/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;
import potionprodigy.Player;
import javax.swing.JOptionPane;

/**
 *
 * @author YJ
 */
public class MainMenuPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Controller controller;

    /**
     * Creates new form MainMenuPanel
     */

    public MainMenuPanel(MainFrame mainFrame, Controller controller) {
        initComponents();

        this.mainFrame = mainFrame;
        this.controller = controller;
        btnBlessCauldron.addActionListener(this::btnBlessCauldronActionPerformed);
    }

    // refresh method to update mainmenu
    public void refreshDisplay() {
        Player player = controller.getCurrentPlayer();

        if (player != null) {
            lblWelcome.setText("Welcome, " + player.getName() + "!");

            lblCrystals.setText("Current Crystals: " + player.getCrystals());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnBrew = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnSpellbook = new javax.swing.JButton();
        btnMarket = new javax.swing.JButton();
        btnBlessCauldron = new javax.swing.JButton();
        btnLoginBonus = new javax.swing.JButton();
        btnSaveAndExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblCrystals = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnBrew.setText("Brew A Potion");
        btnBrew.addActionListener(this::btnBrewActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnBrew, gridBagConstraints);

        btnInventory.setText("Open Inventory");
        btnInventory.addActionListener(this::btnInventoryActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnInventory, gridBagConstraints);

        btnSpellbook.setText("Open Spellbook");
        btnSpellbook.addActionListener(this::btnSpellbookActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnSpellbook, gridBagConstraints);

        btnMarket.setText("Visit Market");
        btnMarket.addActionListener(this::btnMarketActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnMarket, gridBagConstraints);

        btnBlessCauldron.setText("Bless Cauldron");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnBlessCauldron, gridBagConstraints);

        btnLoginBonus.setText("Login Bonus");
        btnLoginBonus.addActionListener(this::btnLoginBonusActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnLoginBonus, gridBagConstraints);

        btnSaveAndExit.setText("Save & Exit");
        btnSaveAndExit.addActionListener(this::btnSaveAndExitActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnSaveAndExit, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblWelcome.setText("Welcome");
        jPanel2.add(lblWelcome, new java.awt.GridBagConstraints());

        lblCrystals.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCrystals.setText("Crystals");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(lblCrystals, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginBonusActionPerformed
        String status = controller.claimLoginBonus();
        if("error".equals(status)){
            JOptionPane.showMessageDialog(this, "Login bonus couldn't be generated", "Login Bonus",JOptionPane.ERROR_MESSAGE);
        } else if("claimed".equals(status)){
            JOptionPane.showMessageDialog(this, "Login bonus already claimed", "Login Bonus",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Login bonus successfully claimed. You gained 1x " + status, "Login Bonus",JOptionPane.INFORMATION_MESSAGE);
        }

                
        
    }//GEN-LAST:event_btnLoginBonusActionPerformed

    private void btnSaveAndExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveAndExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to save and exit the game?",
            "Confirm Save & Exit",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        if(confirm == JOptionPane.YES_OPTION){
            if (controller.saveGame()) {
                JOptionPane.showMessageDialog(this, "Game saved successfully!!!", "Saved game",JOptionPane.INFORMATION_MESSAGE);
                mainFrame.showStart();
            } else {
                JOptionPane.showMessageDialog(this,"Failed to save the game.","Save Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }// GEN-LAST:event_btnSaveAndExitActionPerformed

    private void btnBrewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBrewActionPerformed
        mainFrame.showBrew();
    }// GEN-LAST:event_btnBrewActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInventoryActionPerformed
        mainFrame.showInventory();
    }// GEN-LAST:event_btnInventoryActionPerformed

    private void btnSpellbookActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSpellbookActionPerformed
        mainFrame.showSpellbook();
    }// GEN-LAST:event_btnSpellbookActionPerformed

    private void btnMarketActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMarketActionPerformed
        controller.generateMarket();
        mainFrame.showMarket();
    }// GEN-LAST:event_btnMarketActionPerformed

    private void btnBlessCauldronActionPerformed(java.awt.event.ActionEvent evt) {
        if (controller != null) {
            int result = controller.blessCauldronPay();
            switch(result) {
                case -1:
                    JOptionPane.showMessageDialog(this, "Blessing failed: There are no blessable cauldrons all are usable.",
                        "Bless Cauldron", JOptionPane.WARNING_MESSAGE);
                    break;
                case 0:
                    JOptionPane.showMessageDialog(this,
                        "Blessing failed: You don't have enough crystals(Requires 1000 crystals)", "Bless Cauldron",
                        JOptionPane.WARNING_MESSAGE);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(this, "Cauldron blessed! You now have "
                        + controller.getCurrentPlayer().getInventory().countUsableCauldrons() + " usable cauldrons.",
                        "Bless Cauldron", JOptionPane.INFORMATION_MESSAGE);
                    refreshDisplay();
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Unable to bless cauldron.", "Bless Cauldron",
                        JOptionPane.ERROR_MESSAGE);
                    break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlessCauldron;
    private javax.swing.JButton btnBrew;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLoginBonus;
    private javax.swing.JButton btnMarket;
    private javax.swing.JButton btnSaveAndExit;
    private javax.swing.JButton btnSpellbook;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCrystals;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
