/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import controller.Controller;
import java.awt.CardLayout;

/**
 *
 * @author YJ
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private final Controller controller;
    private final CardLayout cardLayout;
    
    private StartPanel startPanel;
    private MainMenuPanel mainMenuPanel;
    private BrewPanel brewPanel;
    private InventoryPanel inventoryPanel;
    private SpellbookPanel spellbookPanel;
    private MarketPanel marketPanel;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        this.controller = new Controller();
        this.cardLayout = (CardLayout)contentPanel.getLayout();

        this.startPanel = new StartPanel(this, controller);
        this.mainMenuPanel = new MainMenuPanel(this, controller);
        // this.brewPanel = new BrewPanel(this, controller);
        this.inventoryPanel = new InventoryPanel(this, controller);
        // this.spellbookPanel = new SpellbookPanel(this, controller);
        // this.marketPanel = new MarketPanel(this, controller);

        contentPanel.add(startPanel, "START");
        contentPanel.add(mainMenuPanel, "MENU");
        // contentPanel.add(brewPanel, "BREW");
        contentPanel.add(inventoryPanel, "INVENTORY");
        // contentPanel.add(spellbookPanel, "SPELLBOOK");
        // contentPanel.add(marketPanel, "MARKET");
        
        showStart();

        setTitle("Potion Prodigy");
        setLocationRelativeTo(null);
    }

    public void openMainMenu() {
        mainMenuPanel.refreshDisplay();
    }

    public Controller getController() {
        return controller;
    }
    
    public void showStart() {
        cardLayout.show(contentPanel, "START");
    }
    
    public void showMainMenu() {
        mainMenuPanel.refreshDisplay();
        cardLayout.show(contentPanel, "MENU");
    }
    
    public void showBrew() {
        // brewPanel.refreshDisplay();
        cardLayout.show(contentPanel, "BREW");
    }
    
    public void showInventory() {
        inventoryPanel.refreshDisplay();
        cardLayout.show(contentPanel, "INVENTORY");
    }
    
    public void showSpellbook() {
        // spellbookPanel.refreshDisplay();
        cardLayout.show(contentPanel, "SPELLBOOK");
    }
    
    public void showMarket() {
        // marketPanel.refreshDisplay();
        cardLayout.show(contentPanel, "MARKET");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Potion Prodigy");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    // End of variables declaration//GEN-END:variables
}
