/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;
import potionprodigy.Player;
import javax.swing.JOptionPane;

/**
 *
 * @author YJ
 */
public class MainMenuPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Controller controller;

    /**
     * Creates new form MainMenuPanel
     */

    public MainMenuPanel(MainFrame mainFrame, Controller controller) {
        initComponents();

        this.mainFrame = mainFrame;
        this.controller = controller;
    }

    // refresh method to update mainmenu
    public void refreshDisplay() {
        Player player = controller.getCurrentPlayer();

        if (player != null) {
            lblWelcome.setText("Welcome, " + player.getName() + "!");

            lblCrystals.setText("Current Crystals: " + player.getCrystals());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblCrystals = new javax.swing.JLabel();
        btnBrew = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnSpellbook = new javax.swing.JButton();
        btnMarket = new javax.swing.JButton();
        btnBlessCauldron = new javax.swing.JButton();
        btnLoginBonus = new javax.swing.JButton();
        btnSaveAndExit = new javax.swing.JButton();

        lblWelcome.setText("Welcome");

        lblCrystals.setText("Crystals");

        btnBrew.setText("Brew A Potion");
        btnBrew.addActionListener(this::btnBrewActionPerformed);

        btnInventory.setText("Open Inventory");
        btnInventory.addActionListener(this::btnInventoryActionPerformed);

        btnSpellbook.setText("Open Spellbook");
        btnSpellbook.addActionListener(this::btnSpellbookActionPerformed);

        btnMarket.setText("Visit Market");
        btnMarket.addActionListener(this::btnMarketActionPerformed);

        btnBlessCauldron.setText("Bless Cauldron");
        btnBlessCauldron.addActionListener(this::btnBlessCauldronActionPerformed);

        btnLoginBonus.setText("Login Bonus");
        btnLoginBonus.addActionListener(this::btnLoginBonusActionPerformed);

        btnSaveAndExit.setText("Save & Exit");
        btnSaveAndExit.addActionListener(this::btnSaveAndExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveAndExit)
                    .addComponent(btnLoginBonus)
                    .addComponent(btnBlessCauldron)
                    .addComponent(btnMarket)
                    .addComponent(btnSpellbook)
                    .addComponent(btnInventory)
                    .addComponent(btnBrew)
                    .addComponent(lblCrystals)
                    .addComponent(lblWelcome))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCrystals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBrew)
                .addGap(18, 18, 18)
                .addComponent(btnInventory)
                .addGap(18, 18, 18)
                .addComponent(btnSpellbook)
                .addGap(18, 18, 18)
                .addComponent(btnMarket)
                .addGap(18, 18, 18)
                .addComponent(btnBlessCauldron)
                .addGap(18, 18, 18)
                .addComponent(btnLoginBonus)
                .addGap(18, 18, 18)
                .addComponent(btnSaveAndExit)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginBonusActionPerformed
        int status = controller.claimLoginBonus();
        switch(status){
            case -1: 
                JOptionPane.showMessageDialog(this, "Login bonus couldn't be generated", "Login Bonus",JOptionPane.ERROR_MESSAGE);
                break;
            case 0:
                JOptionPane.showMessageDialog(this, "Login bonus already claimed", "Login Bonus",JOptionPane.INFORMATION_MESSAGE);
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Login bonus successfully claimed", "Login Bonus",JOptionPane.INFORMATION_MESSAGE);
                break;
        }
    }//GEN-LAST:event_btnLoginBonusActionPerformed

    private void btnSaveAndExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveAndExitActionPerformed

        if (controller.saveGame()) {
            JOptionPane.showMessageDialog(this, "Game saved successfully!!!", "Saved game",JOptionPane.INFORMATION_MESSAGE);

            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(this,"Failed to save the game.","Save Error", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnSaveAndExitActionPerformed

    private void btnBrewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBrewActionPerformed
        mainFrame.showBrew();
    }// GEN-LAST:event_btnBrewActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInventoryActionPerformed
        mainFrame.showInventory();
    }// GEN-LAST:event_btnInventoryActionPerformed

    private void btnSpellbookActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSpellbookActionPerformed
        mainFrame.showSpellbook();
    }// GEN-LAST:event_btnSpellbookActionPerformed

    private void btnMarketActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMarketActionPerformed
        controller.generateMarket();
        mainFrame.showMarket();
    }// GEN-LAST:event_btnMarketActionPerformed

    private void btnBlessCauldronActionPerformed(java.awt.event.ActionEvent evt) {
        if (controller != null) {
            int result = controller.blessCauldronPay();
            switch(result) {
                case -1:
                    JOptionPane.showMessageDialog(this, "Blessing failed: There are no blessable cauldrons",
                        "Bless Cauldron", JOptionPane.WARNING_MESSAGE);
                    break;
                case 0:
                    JOptionPane.showMessageDialog(this,
                        "Blessing failed: You don't have enough crystals(Requires 1000 crystals)", "Bless Cauldron",
                        JOptionPane.WARNING_MESSAGE);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(this, "Cauldron blessed! You now have "
                        + controller.getCurrentPlayer().getInventory().countUsableCauldrons() + " usable cauldrons.",
                        "Bless Cauldron", JOptionPane.INFORMATION_MESSAGE);
                    refreshDisplay();
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Unable to bless cauldron.", "Bless Cauldron",
                        JOptionPane.ERROR_MESSAGE);
                    break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlessCauldron;
    private javax.swing.JButton btnBrew;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLoginBonus;
    private javax.swing.JButton btnMarket;
    private javax.swing.JButton btnSaveAndExit;
    private javax.swing.JButton btnSpellbook;
    private javax.swing.JLabel lblCrystals;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
