/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;
import javax.swing.ButtonGroup;

/**
 *
 * @author YJ
 */
public class MarketPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private Controller controller;
    private java.util.List<Integer> selectedSlotNumbers = new java.util.ArrayList<>();
    
    /**
     * Creates new form MarketPanel
     */
    public MarketPanel(MainFrame mainFrame, Controller controller) {
        initComponents();

        this.mainFrame = mainFrame;
        this.controller = controller;

        javax.swing.ButtonGroup modeGroup = new javax.swing.ButtonGroup();
        modeGroup.add(radioBtnBuy);
        modeGroup.add(radioBtnSell);
        radioBtnBuy.setSelected(true);

    }

    public void refreshDisplay() {
        if (radioBtnBuy.isSelected()) {
            refreshBuyView();
        } else {
            refreshSellView();
        }
    }

    public void refreshBuyView() {
        int totalCost = 0;
        int i =0;
        if (controller != null && controller.getMarket() != null) {
            java.util.ArrayList<potionprodigy.Listing> listings = controller.getAvailableListings();
            javax.swing.JPanel[] buySlots = {buySlot1, buySlot2, buySlot3, buySlot4, buySlot5, buySlot6, buySlot7, buySlot8};

            for (i = 0; i < buySlots.length; i++) {
                buySlots[i].removeAll(); 
                buySlots[i].setLayout(new java.awt.BorderLayout());

                if (i < listings.size()) {
                    potionprodigy.Listing listing = listings.get(i);
                    int slotNumber = listing.getSlotNumber();
                    ItemCard card = new ItemCard(listing);
                
                    if (selectedSlotNumbers.contains(slotNumber)) {
                        card.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GREEN, 3));
                        totalCost += (listing.getUnitPrice() * listing.getQuantity());
                    } else {
                        card.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK, 1));
                    }
                
                    card.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseClicked(java.awt.event.MouseEvent e) {
                            toggleSlotSelection(slotNumber);
                        }
                    });
                buySlots[i].add(card, java.awt.BorderLayout.CENTER);
            }
            buySlots[i].revalidate();
            buySlots[i].repaint();
        }
            totalCostLabel.setText("Total: " + totalCost + " Crystals");
        }
    }

    private void toggleSlotSelection(int slotNumber) {
        if (selectedSlotNumbers.contains(slotNumber)) {
            selectedSlotNumbers.remove(Integer.valueOf(slotNumber));
        } else {
            selectedSlotNumbers.add(slotNumber);
        }
        refreshBuyView();
    }

    public void refreshSellView() {
        // WLAAAFDSHKLFSDHF
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        radioBtnBuy = new javax.swing.JRadioButton();
        radioBtnSell = new javax.swing.JRadioButton();
        centerCardPanel = new javax.swing.JPanel();
        buyItemSlots = new javax.swing.JPanel();
        buySlot1 = new javax.swing.JPanel();
        buySlot2 = new javax.swing.JPanel();
        buySlot3 = new javax.swing.JPanel();
        buySlot4 = new javax.swing.JPanel();
        buySlot5 = new javax.swing.JPanel();
        buySlot6 = new javax.swing.JPanel();
        buySlot7 = new javax.swing.JPanel();
        buySlot8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Footer = new javax.swing.JPanel();
        totalCostLabel = new javax.swing.JLabel();
        bottomButtonsContainer = new javax.swing.JPanel();
        btnConfirm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        Header.setPreferredSize(new java.awt.Dimension(242, 50));
        Header.setLayout(new javax.swing.BoxLayout(Header, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Market");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(0.5F);
        Header.add(jLabel1);

        radioBtnBuy.setText("Buy");
        radioBtnBuy.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        radioBtnBuy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        radioBtnBuy.addActionListener(this::radioBtnBuyActionPerformed);
        jPanel14.add(radioBtnBuy);

        radioBtnSell.setText("Sell");
        radioBtnSell.addActionListener(this::radioBtnSellActionPerformed);
        jPanel14.add(radioBtnSell);

        Header.add(jPanel14);

        jPanel1.add(Header, java.awt.BorderLayout.NORTH);

        centerCardPanel.setLayout(new java.awt.CardLayout());

        buyItemSlots.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        buyItemSlots.setLayout(new java.awt.GridLayout(2, 4, 10, 10));

        buySlot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyItemSlots.add(buySlot1);

        buySlot2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyItemSlots.add(buySlot2);

        buySlot3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyItemSlots.add(buySlot3);

        buySlot4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyItemSlots.add(buySlot4);

        buySlot5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyItemSlots.add(buySlot5);

        buySlot6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyItemSlots.add(buySlot6);

        buySlot7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyItemSlots.add(buySlot7);

        buySlot8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buyItemSlots.add(buySlot8);

        centerCardPanel.add(buyItemSlots, "card2");

        jPanel2.setLayout(new java.awt.GridLayout(2, 4, 10, 0));
        jScrollPane1.setViewportView(jPanel2);

        centerCardPanel.add(jScrollPane1, "card4");

        jPanel1.add(centerCardPanel, java.awt.BorderLayout.CENTER);

        Footer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        Footer.setPreferredSize(new java.awt.Dimension(200, 100));
        Footer.setLayout(new java.awt.BorderLayout());

        totalCostLabel.setText("Total:");
        Footer.add(totalCostLabel, java.awt.BorderLayout.CENTER);

        bottomButtonsContainer.setPreferredSize(new java.awt.Dimension(171, 33));

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);
        bottomButtonsContainer.add(btnConfirm);

        jButton2.setText("Back");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        bottomButtonsContainer.add(jButton2);

        Footer.add(bottomButtonsContainer, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(Footer, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (mainFrame != null) {
            mainFrame.showMainMenu();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioBtnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnBuyActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) centerCardPanel.getLayout();
        cl.show(centerCardPanel, "card2"); // Opens Buy view
    
        refreshDisplay();
    }//GEN-LAST:event_radioBtnBuyActionPerformed

    private void radioBtnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnSellActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) centerCardPanel.getLayout();
        cl.show(centerCardPanel, "card4"); // Opens Buy view
    
        refreshDisplay();
    }//GEN-LAST:event_radioBtnSellActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel bottomButtonsContainer;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JPanel buyItemSlots;
    private javax.swing.JPanel buySlot1;
    private javax.swing.JPanel buySlot2;
    private javax.swing.JPanel buySlot3;
    private javax.swing.JPanel buySlot4;
    private javax.swing.JPanel buySlot5;
    private javax.swing.JPanel buySlot6;
    private javax.swing.JPanel buySlot7;
    private javax.swing.JPanel buySlot8;
    private javax.swing.JPanel centerCardPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioBtnBuy;
    private javax.swing.JRadioButton radioBtnSell;
    private javax.swing.JLabel totalCostLabel;
    // End of variables declaration//GEN-END:variables
}
