/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;
/**
 *
 * @author YJ
 */
public class MarketPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private Controller controller;

    
    /**
     * Creates new form MarketPanel
     */
    public MarketPanel(MainFrame mainFrame, Controller controller) {
        initComponents();

        this.mainFrame = mainFrame;
        this.controller = controller;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        radioBtnBuy = new javax.swing.JRadioButton();
        radioBtnSell = new javax.swing.JRadioButton();
        centerCardPanel = new javax.swing.JPanel();
        butItemSlots = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Footer = new javax.swing.JPanel();
        totalCostLabel = new javax.swing.JLabel();
        bottomButtonsContainer = new javax.swing.JPanel();
        btnConfirm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        Header.setPreferredSize(new java.awt.Dimension(242, 50));
        Header.setLayout(new javax.swing.BoxLayout(Header, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Market");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(0.5F);
        Header.add(jLabel1);

        radioBtnBuy.setText("Buy");
        radioBtnBuy.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        radioBtnBuy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        radioBtnBuy.addActionListener(this::radioBtnBuyActionPerformed);
        jPanel14.add(radioBtnBuy);

        radioBtnSell.setText("Sell");
        radioBtnSell.addActionListener(this::radioBtnSellActionPerformed);
        jPanel14.add(radioBtnSell);

        Header.add(jPanel14);

        jPanel1.add(Header, java.awt.BorderLayout.NORTH);

        centerCardPanel.setLayout(new java.awt.CardLayout());

        butItemSlots.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        butItemSlots.setLayout(new java.awt.GridLayout(2, 4, 10, 10));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        butItemSlots.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        butItemSlots.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        butItemSlots.add(jPanel7);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        butItemSlots.add(jPanel9);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        butItemSlots.add(jPanel13);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        butItemSlots.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        butItemSlots.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        butItemSlots.add(jPanel12);

        centerCardPanel.add(butItemSlots, "card2");

        jPanel2.setLayout(new java.awt.GridLayout(2, 4, 10, 0));
        jScrollPane1.setViewportView(jPanel2);

        centerCardPanel.add(jScrollPane1, "card4");

        jPanel1.add(centerCardPanel, java.awt.BorderLayout.CENTER);

        Footer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        Footer.setPreferredSize(new java.awt.Dimension(200, 100));
        Footer.setLayout(new java.awt.BorderLayout());

        totalCostLabel.setText("Total:");
        Footer.add(totalCostLabel, java.awt.BorderLayout.CENTER);

        bottomButtonsContainer.setPreferredSize(new java.awt.Dimension(171, 33));

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);
        bottomButtonsContainer.add(btnConfirm);

        jButton2.setText("Back");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        bottomButtonsContainer.add(jButton2);

        Footer.add(bottomButtonsContainer, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(Footer, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioBtnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnBuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnBuyActionPerformed

    private void radioBtnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnSellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnSellActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel bottomButtonsContainer;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JPanel butItemSlots;
    private javax.swing.JPanel centerCardPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioBtnBuy;
    private javax.swing.JRadioButton radioBtnSell;
    private javax.swing.JLabel totalCostLabel;
    // End of variables declaration//GEN-END:variables
}
