/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;
import javax.swing.ButtonGroup;
import potionprodigy.Inventory;
import potionprodigy.Player;
import potionprodigy.Recipe;
import gui.components.RecipeCard;
import gui.components.Theme;

/**
 * displays unlocked recipes that may be selected and brewed using the player's current inventory
 */
public class RecipePanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private Controller controller;
    
    private Recipe selectedRecipe;
    private ButtonGroup recipeButtonGroup;
    
    /**
     * Creates a recipe panel connected to the application.
     *
     * @param mainFrame application window used for navigation
     * @param controller controller used to perform brewing operations
     */
    public RecipePanel(MainFrame mainFrame, Controller controller) {
        initComponents();
        
        this.mainFrame = mainFrame;
        this.controller = controller;
        
        recipeListPanel.setLayout(new javax.swing.BoxLayout(recipeListPanel, javax.swing.BoxLayout.Y_AXIS));
        recipeScrollPane.getVerticalScrollBar().setUnitIncrement(15);
    }
    /**
     * Rebuilds the recipe list, clears the previous selection, and updates the
     * displayed usable-cauldron count.
     */
    public void refreshDisplay() {
        recipeListPanel.removeAll();
        
        selectedRecipe = null;
        recipeButtonGroup = new ButtonGroup();
        btnBrew.setEnabled(false);
        
        Player player = controller.getCurrentPlayer();
        
        if (player != null) {
            Inventory inventory = player.getInventory();
            
            lblCauldrons.setText("Cauldrons: " + inventory.countUsableCauldrons()
                + " usable / " + inventory.countUnusableCauldrons() + " unusable");
            
            for (Recipe recipe : player.getRecipeBook().getUnlockedRecipes()) {
                RecipeCard recipeCard = new RecipeCard(recipe, inventory, recipeButtonGroup, true);
                Theme.apply(recipeCard);
                
                recipeCard.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, recipeCard.getPreferredSize().height));
                
                recipeCard.getRecipeRadioButton().
                        addItemListener(event -> {
                            if (event.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                                selectedRecipe = recipeCard.getRecipe();
                                btnBrew.setEnabled(true);
                            }
                        });
                
                recipeListPanel.add(recipeCard);
                recipeListPanel.add(javax.swing.Box.createVerticalStrut(8));
            }
        } else {
            lblCauldrons.setText("Usable Cauldrons: 0");
        }
        
        recipeListPanel.revalidate(); // remeasure size
        recipeListPanel.repaint(); // redraw windows/component
        
        javax.swing.SwingUtilities.invokeLater(() -> {
            recipeScrollPane.getVerticalScrollBar().setValue(0); // reset scrollbar to top
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnBrew = new javax.swing.JButton();
        lblText = new javax.swing.JLabel();
        lblCauldrons = new javax.swing.JLabel();
        recipeScrollPane = new javax.swing.JScrollPane();
        recipeListPanel = new javax.swing.JPanel();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack);

        btnBrew.setText("Brew a Concoction");
        btnBrew.addActionListener(this::btnBrewActionPerformed);
        jPanel1.add(btnBrew);

        lblText.setText("Select a recipe to brew.");

        lblCauldrons.setText("Cauldrons");

        recipeScrollPane.setBorder(null);

        javax.swing.GroupLayout recipeListPanelLayout = new javax.swing.GroupLayout(recipeListPanel);
        recipeListPanel.setLayout(recipeListPanelLayout);
        recipeListPanelLayout.setHorizontalGroup(
            recipeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        recipeListPanelLayout.setVerticalGroup(
            recipeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        recipeScrollPane.setViewportView(recipeListPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCauldrons))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(recipeScrollPane)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblText)
                    .addComponent(lblCauldrons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recipeScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Returns to the brewing-mode selection screen.
     *
     * @param evt generated button action event
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.showBrew();
    }//GEN-LAST:event_btnBackActionPerformed
    /**
     * Attempts to brew the currently selected recipe.
     *
     * @param evt generated button action event
     */
    private void btnBrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrewActionPerformed
        int earnedCrystals, confirmation;
        boolean success;
        
        if (this.selectedRecipe != null) {
            confirmation = javax.swing.JOptionPane.showConfirmDialog(this, "Brew " + selectedRecipe.getConcoctionName() + 
                    "?\n\n" + "Sale value: " + selectedRecipe.getSaleValue() + " crystals.", "Confirm Brewing", 
                    javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);
            
            if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
                earnedCrystals = selectedRecipe.getSaleValue();
                success = controller.brewRecipe(selectedRecipe);
                if (success) {
                    javax.swing.JOptionPane.showMessageDialog(this, selectedRecipe.getConcoctionName() + 
                            " was successfully brewed!\n" + "You earned " + earnedCrystals + 
                            " crystals.", "Brewing Successful",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "The concoction could not be brewed.\n" + 
                            "Check your ingredients and recipe status.", 
                            "Brewing Failed",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
                refreshDisplay();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a craftable recipe.", 
                    "No Recipe Selected", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBrewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCauldrons;
    private javax.swing.JLabel lblText;
    private javax.swing.JPanel recipeListPanel;
    private javax.swing.JScrollPane recipeScrollPane;
    // End of variables declaration//GEN-END:variables
}
