/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;
import gui.components.RecipeCard;
import gui.components.Theme;
import potionprodigy.Player;
import potionprodigy.Inventory;
import potionprodigy.Recipe;

/**
 *
 * @author YJ
 */
public class SpellbookPanel extends javax.swing.JPanel {
    MainFrame mainFrame;
    Controller controller;
    /**
     * Creates new form SpellbookPanel
     */
    public SpellbookPanel() {
        initComponents();
    }
    
    public SpellbookPanel(MainFrame mainFrame, Controller controller) {
        initComponents();
        
        this.mainFrame = mainFrame;
        this.controller = controller;
        
        recipeListPanel.setLayout(new javax.swing.BoxLayout(recipeListPanel, javax.swing.BoxLayout.Y_AXIS));
        recipeScrollPane.getVerticalScrollBar().setUnitIncrement(15);
    }
    
    public void refreshDisplay() {
        recipeListPanel.removeAll();
    
        Player player = controller.getCurrentPlayer();

        if (player != null) {
            Inventory inventory = player.getInventory();
        
            for (Recipe recipe : player.getRecipeBook().getUnlockedRecipes()) {
                RecipeCard recipeCard = new RecipeCard(recipe, inventory, null, false);
                Theme.apply(recipeCard);
                recipeCard.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, recipeCard.getPreferredSize().height));
            
                recipeListPanel.add(recipeCard);
                recipeListPanel.add(javax.swing.Box.createVerticalStrut(8));
            }
        }
    
        recipeListPanel.revalidate();
        recipeListPanel.repaint();
        
        javax.swing.SwingUtilities.invokeLater(() -> {
            recipeScrollPane.getVerticalScrollBar().setValue(0);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recipeScrollPane = new javax.swing.JScrollPane();
        recipeListPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        recipeScrollPane.setBorder(null);

        recipeListPanel.setLayout(new javax.swing.BoxLayout(recipeListPanel, javax.swing.BoxLayout.LINE_AXIS));
        recipeScrollPane.setViewportView(recipeListPanel);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recipeScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 316, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recipeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.showMainMenu();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel recipeListPanel;
    private javax.swing.JScrollPane recipeScrollPane;
    // End of variables declaration//GEN-END:variables
}
