/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;

/**
 *
 * @author YJ
 */
public class StartPanel extends javax.swing.JPanel {
    
    private MainFrame mainFrame;
    private Controller controller;
    
    /**
     * Creates new form StartPanel
     */
    public StartPanel() {
        initComponents();
    }
    
    public StartPanel(MainFrame mainFrame, Controller controller) {
        initComponents();

        this.mainFrame = mainFrame;
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        btnNewGame = new javax.swing.JButton();
        btnLoadGame = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        lblTitle.setText("Potion Prodigy");

        lblPlayerName.setText("Player Name:");

        txtPlayerName.setText("...");
        txtPlayerName.addActionListener(this::txtPlayerNameActionPerformed);

        btnNewGame.setText("New Game");
        btnNewGame.addActionListener(this::btnNewGameActionPerformed);

        btnLoadGame.setText("Load Game");

        lblMessage.setText("Enter your player name to begin.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(btnNewGame)
                .addGap(131, 131, 131)
                .addComponent(btnLoadGame)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPlayerName)
                                .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(39, 39, 39)
                .addComponent(lblPlayerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewGame)
                    .addComponent(btnLoadGame))
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlayerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayerNameActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        String playerName = txtPlayerName.getText().trim();
        boolean createGame = false;
        
        if (playerName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Please enter a player name.", "Missing Player Name", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            createGame = true;
            
            if (controller.saveExists(playerName)) {
                int answer = javax.swing.JOptionPane.showConfirmDialog(this, 
                        "A save named \"" + playerName + 
                        "\" already exists.\nOverwrite it?", "Overwrite Save",
                        javax.swing.JOptionPane.YES_NO_OPTION, 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                
                createGame = answer == javax.swing.JOptionPane.YES_OPTION;
            }
        }
        
        if (createGame) {
            controller.createNewGame(playerName);
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "New game created for " + playerName + ".", "New Game", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            mainFrame.openMainMenu();
        }
    }//GEN-LAST:event_btnNewGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadGame;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables
}
