/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;

/**
 *
 * @author YJ
 */
public class StartPanel extends javax.swing.JPanel {
    
    private MainFrame mainFrame;
    private Controller controller;
    
    /**
     * Creates new form StartPanel
     */
    public StartPanel() {
        initComponents();
    }
    
    public StartPanel(MainFrame mainFrame, Controller controller) {
        initComponents();

        this.mainFrame = mainFrame;
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblPlayerName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnNewGame = new javax.swing.JButton();
        btnLoadGame = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(new java.awt.Font("Monospaced", 1, 70)); // NOI18N
        lblTitle.setText("POTION PRODIGY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 24, 24, 25);
        jPanel1.add(lblTitle, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblPlayerName.setText("Player Name:    ");
        jPanel2.add(lblPlayerName, new java.awt.GridBagConstraints());

        btnNewGame.setText("New Game");
        btnNewGame.addActionListener(this::btnNewGameActionPerformed);

        btnLoadGame.setText("Load Game");
        btnLoadGame.addActionListener(this::btnLoadGameActionPerformed);

        lblMessage.setText("Enter your player name to begin.");

        txtPlayerName.setToolTipText("Enter player name");
        txtPlayerName.setActionCommand("<Not Set>");
        txtPlayerName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPlayerName.setMinimumSize(new java.awt.Dimension(140, 22));
        txtPlayerName.setName("Enter player name here"); // NOI18N
        txtPlayerName.addActionListener(this::txtPlayerNameActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnNewGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoadGame)
                .addGap(149, 149, 149))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPlayerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(264, 264, 264))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMessage)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewGame)
                    .addComponent(btnLoadGame))
                .addGap(33, 33, 33))
        );

        txtPlayerName.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlayerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayerNameActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        String playerName = txtPlayerName.getText().trim();
        boolean createGame = false;
        
        if (playerName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Please enter a player name.", "Missing Player Name", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            createGame = true;
            
            if (controller.saveExists(playerName)) {
                int answer = javax.swing.JOptionPane.showConfirmDialog(this, 
                        "A save named \"" + playerName + 
                        "\" already exists.\nOverwrite it?", "Overwrite Save",
                        javax.swing.JOptionPane.YES_NO_OPTION, 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                
                createGame = answer == javax.swing.JOptionPane.YES_OPTION;
            }
        }
        
        if (createGame) {
            controller.createNewGame(playerName);
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "New game created for " + playerName + ".", "New Game", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            mainFrame.showMainMenu();
        }
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btnLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadGameActionPerformed
        String playerName = txtPlayerName.getText().trim();
        
        if (playerName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Please enter the name of the save to load.", 
                    "Missing Save Name", javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            boolean loaded = controller.loadGame(playerName);
            
            if (loaded) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Welcome back, " + playerName + "!", "Game Loaded", 
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                mainFrame.showMainMenu();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "No valid save was found for \"" + playerName + "\".", 
                        "Load Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLoadGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadGame;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables
}
