/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import controller.Controller;

/**
 *
 * @author YJ
 */
public class StartPanel extends javax.swing.JPanel {
    
    private MainFrame mainFrame;
    private Controller controller;
    
    /**
     * Creates new form StartPanel
     */
    public StartPanel() {
        initComponents();
    }
    
    public StartPanel(MainFrame mainFrame, Controller controller) {
        initComponents();

        this.mainFrame = mainFrame;
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        btnNewGame = new javax.swing.JButton();
        btnLoadGame = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        lblTitle.setText("Potion Prodigy");

        lblPlayerName.setText("Player Name:");

        txtPlayerName.setText("Enter player name here");
        txtPlayerName.setToolTipText("");
        txtPlayerName.setActionCommand("<Not Set>");
        txtPlayerName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPlayerName.setMinimumSize(new java.awt.Dimension(140, 22));
        txtPlayerName.setName("Enter player name here"); // NOI18N
        txtPlayerName.addActionListener(this::txtPlayerNameActionPerformed);

        btnNewGame.setText("New Game");
        btnNewGame.addActionListener(this::btnNewGameActionPerformed);

        btnLoadGame.setText("Load Game");
        btnLoadGame.addActionListener(this::btnLoadGameActionPerformed);

        lblMessage.setText("Enter your player name to begin.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnNewGame)
                        .addGap(131, 131, 131)
                        .addComponent(btnLoadGame))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lblPlayerName))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(84, 84, 84)
                .addComponent(lblPlayerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewGame)
                    .addComponent(btnLoadGame))
                .addGap(111, 111, 111))
        );

        txtPlayerName.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlayerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayerNameActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        String playerName = txtPlayerName.getText().trim();
        boolean createGame = false;
        
        if (playerName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Please enter a player name.", "Missing Player Name", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            createGame = true;
            
            if (controller.saveExists(playerName)) {
                int answer = javax.swing.JOptionPane.showConfirmDialog(this, 
                        "A save named \"" + playerName + 
                        "\" already exists.\nOverwrite it?", "Overwrite Save",
                        javax.swing.JOptionPane.YES_NO_OPTION, 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                
                createGame = answer == javax.swing.JOptionPane.YES_OPTION;
            }
        }
        
        if (createGame) {
            controller.createNewGame(playerName);
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "New game created for " + playerName + ".", "New Game", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            mainFrame.openMainMenu();
        }
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btnLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadGameActionPerformed
        String playerName = txtPlayerName.getText().trim();
        
        if (playerName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Please enter the name of the save to load.", 
                    "Missing Save Name", javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            boolean loaded = controller.loadGame(playerName);
            
            if (loaded) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Welcome back, " + playerName + "!", "Game Loaded", 
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "No valid save was found for \"" + playerName + "\".", 
                        "Load Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLoadGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadGame;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables
}
